### GET request to check if customer with id exists
#GET http://localhost:8090/api/v1/customers/exists/4257fc33-5c44-4216-96b7-dda39864f56f
GET http://localhost:8222/api/v1/customers/exists/4257fc33-5c44-4216-96b7-dda39864f56f
###