spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/users
    driver-class-name: org.postgresql.Driver
    username: erenb
    password: 123456

    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        dll-auto: validate

    flyway:
      enabled: true
      baseline-on-migrate: true
      baseline-description: "init"
      baseline-version: 0
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}

server:
  port: 8030

logging:
  level:
    root: info

jwt:
  secret: rH9l8fi1ZCfwEcPAB964cRfLAAH4LM+QTC2TrKLcKrg=