spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/customer
    driver-class-name: org.postgresql.Driver
    username: erenb
    password: 123456

    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        dll-auto: create-drop

  sql:
    init:
      mode: always

server:
  port: 8090

logging:
  level:
    root: info