spring:
  h2:
    console:
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: erenb
    password: 123456

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: create-drop

  sql:
    init:
      mode: always

server:
  port: 8090

logging:
  level:
    root: info