spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/order
    driver-class-name: org.postgresql.Driver
    username: erenb
    password: 123456

    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        dll-auto: create-drop

  sql:
    init:
      mode: always

  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.value.default.type: com.ecommerce.order.kafka.OrderConfirmation
        spring.json.type.mapping: orderConfirmation:com.ecommerce.order.kafka.OrderConfirmation

server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments