spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: erenb
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  sql:
    init:
      mode: always

server:
  port: 8050